# Generated by Django 2.2.7 on 2020-02-12 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Courier'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 21, 44, 54, 414748)),
        ),
    ]
